### ISSUE TITLE
1.3 update

### ISSUE THREAD

**Issue by Epicguru** [krafs/RimRef#1]
I'm sure you're busy or have already been asked this through another channel, but is there a possibility of the package being updated the the 1.3 beta assembly? I'm using this package for many mods to enable CI, and it's a really valuable tool for me.

Many thanks.

**Comment by krafs** [comment]
Hi!

I've been uploading 1.3-beta packages these last few days. Are they not appearing for you?

Here's the latest:

https://www.nuget.org/packages/Krafs.Rimworld.Ref/1.3.3052-beta

**Comment by Epicguru** [comment]
Ah I didn't spot that they were pre-releases so they weren't showing up for me, my bad!
Thanks again, great tool.
