### ISSUE TITLE
Error: No references or content files compatible with '.NETFramework,Version=v4.7.2'?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [krafs/RimRef#2]
Hm. Trying to add this to a Hello, World-style solution in Visual Studio 2017 yields this:

```
Error: Could not install package 'Krafs.Rimworld.Ref 1.3.3087'.
   You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2',
   but the package does not contain any assembly references or content files that are compatible
   with that framework. For more information, contact the package author.				
```

(There's no mention of an option to migrate to `PackageReference`; and I don't seem to have a `packages.config` file. I'm guessing, then, that the PackageReference-migration-thing isn't the cause?)

Is "net472" not the correct version to be targeting? That's what's suggested on the Wiki; and got some corroboration on the Discord that that was the correct choice …

**Comment by ELLIOTTCABLE** [comment]
Okay, so it turns out, you can't 'migrate to PackageReference' until you have at least one dependency. Which, an empty hello-world project does not.

Adding Harmony *first*, so that I had at least one dependency to migrate, allowed me access to the migration tool; once I was able to run it, I could install this successfully. Strange.

**Comment by krafs** [comment]
I didn't know about that. I guess the migration option is somehow enabled by the project having a packages.config to begin with. 
I usually create my new mod projects with the library template, but then replace the entire csproj manually to SDK-style instead, like [this](https://gist.github.com/krafs/5f6c75ab198823e270cdaaa1146e693d). That enables PackageReferences by default.

But I'm glad you got it working :)
